backend:
  name: git-gateway
  # test
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "content"
    label: "Content"
    files:
    - label: "Header"
      name: "header"
      file: "content/header.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Sub Title", name: "subtitle", widget: "string"}
        - { label: "Image", name: "image", widget: "image", allow_multiple: false, choose_url: false }
    - label: "Sections"
      name: "sections"
      file: "content/section.md"
      fields:
        - label: 'Section'
          name: "section"
          widget: list
          fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Body", name: "body", widget: "text"}
          - { label: "Image", name: "image", widget: "image", allow_multiple: false, choose_url: false }
    - name: "linksleft"
      label: "Links Left"
      file: "content/linksleft.md"
      fields:
        - label: "Link"
          name: "link"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "URL", name: "url", widget: "string"}
    - name: "linksright"
      label: "Links Right"
      file: "content/linksright.md"
      fields:
        - label: "Link"
          name: "link"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "URL", name: "url", widget: "string"}
    - label: "Footer"
      name: "footer"
      file: "content/footer.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "string"}


