backend:
  name: git-gateway
  # test
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "content"
    label: "Content"
    files:
    - name: "header"
      label: "Header"
      file: "content/header.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Sub Title", name: "subtitle", widget: "string"}
        - { label: "Image", name: "image", widget: "image", allow_multiple: false, choose_url: false }
    - name: "sections"
      label: "Sections"
      file: "content/sections.md"
      fields:
        - name: 'sections'
          widget: list
          fields:
          - { label: "Slug", name: "slug", widget: "string"}
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Body", name: "body", widget: "text"}
          - { label: "Image", name: "image", widget: "image", allow_multiple: false, choose_url: false }
    - name: "reads & links"
      label: "Reads & Links"
      file: "content/readsandlinks.md"
      fields:
        - name: 'reads'
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "URL", name: "url", widget: "string"}
        - name: 'links'
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "URL", name: "url", widget: "string"}
    - name: "contact"
      label: "Contact"
      file: "content/contact.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "string"}
    - name: "footer"
      label: "Footer"
      file: "content/footer.md"
      fields:
        - { label: "Body", name: "body", widget: "string"}


